### ISSUE TITLE
[BUG] Custom sub categories and playlists don't appear in Viewer after april 2020 content refresh

### ISSUE THREAD

**Issue by tomrune** [pnp/custom-learning-office-365#239]
## Describe the bug

I am a consultant creating content for a customer in their learning path installation. I have created  additional customer specific content as 4 custom sub categories under the "Scenarios" category. Two of these were visible with playlists underneath and all worked well. 

After the april 20 content update, custom created sub categories in their installation no longer show in the LearningViewer, despite having the eye icon enabled. They were visible prior. 
Clicking the eye on or off changes the icon but CustomLearningViewer still refuse to show them. 

I created a new subcategory and moved a playlist to it from the old one. That one shows up in the CustomLearningviewer. I then shifted the remaining playlists over, but they do not show (i.e. only the first playlist shows, the others do not appear in the viewer). This looks strange as there is no hide/show playlist feature, so it only shows 1 out of 5 in the category.

I attempted to do the same with one other sub category and the new sub cateogry one does not show, thus I cannot see the playlists either.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

I would expect existing content to be preserved and new and existing sub categories to show, as well as all the playlists in them. 

### Screenshots

<img width="635" alt="Bug1" src="https://user-images.githubusercontent.com/14229801/78645875-7b874680-78b8-11ea-9f35-906cfdc77a5c.png">
<img width="522" alt="Bug2" src="https://user-images.githubusercontent.com/14229801/78645876-7cb87380-78b8-11ea-8166-a64c9ebfd816.png">

### Learning Pathways version number

3.0.4.0

### Additional context

>Add any other context about the problem here.

**Comment by tomrune** [comment]
Btw, I have seen comments about caching, so I cleared browser cache and navigated in the same tab between admin and viewer.

**Comment by tomrune** [comment]
This seems related to the issue of not having a value for Technology. When adding technology, the playlists appear, thus the subcategories appear. 

Given the version number they seem to have though, it is a bit strange that this issue should still be there.

**Comment by juliemturner** [comment]
Yep, based on the responses there is absolutely a bug here.  Thus far I haven't been able to reproduce it or find someone willing to work with me on it. It can be fixed by setting a technology but you absolutely shouldn't have to do that. If you're willing to help let me know.  What would be an interesting test, if you set the technology and then set it back to blank what happens?  Just to be clear the content update shouldn't have anything to do with anything... so it's somewhat odd issue.

**Comment by juliemturner** [comment]
I dove into the source code and validated that as long as the playlists technology is a null length string (aka "") the playlists should show up, this was the implemented fix.  Is there any way you can share the JSON from a playlist that isn't showing up in the web part? Ideally, can you make sure you're using the view full of the webpart, a good place to easily get to this is by using CustomLearningViewer.aspx.

**Comment by tomrune** [comment]
I will happily share anything that would help. I am only using CustomLearningViewer.aspx page. 
I confirmed that I need to have a value for Technology for the playlists to show up in the customer environment. 

Of course, murphys law strikes again. I went to the customer to grab the json today and of course, now the problem isn't occurring and I cannot reproduce it. Nevertheless here is the json of a previously affected playlist: 
`{"Id":"20","Title":"Bli kjent med Learning Path (norsk)","Image":"https://pnp.github.io/custom-learning-office-365/learningpathways/v3/images/playlists/playlist_bw.png","LevelId":"f800c81b-ba2b-4b0f-9de5-3d42a0f45202","AudienceId":"28583661-f6fe-4ddb-b50f-fc73a20d3ae7","TechnologyId":"","SubjectId":"","Source":"Tenant","CatId":"50ab3b48-958e-4fdf-bc4a-f1ee9c05a844","Description":"Learning Path er et unikt nytt kurssystem i SharePoint som består av en blanding av innhold fra Microsoft og CustomerName. \nI dette intro-kurset blir du litt kjent med hvordan du navigerer i kursene og modulene. ","StatusTagId":"","StatusNote":"","Assets":["24"]}`

I am now able to see custom subcategories containing a playlist without technology applied to the playlist inside. The playlist in question was never assigned a technology. 
I then went to a playlist and removed the technology from it and it too appears in the subcategory, though it seems sorting is "technology, name" ascending? Or, the de-technology-fied playlist appeared before the ones with technology set, and when I added tech back to it, it went back to its original place.

I will look out for this occurring again elsewhere and attach any data that is of use then. :) 

We have Learning Pathways in our own tenant, at the same version, and I was not able to reproduce their problem there, which is when I opened this issue in case there was some kind of cache or manual procedure that could be done.

**Comment by juliemturner** [comment]
Hmm, well... this does support that the bug was fixed.  Is it possible the order of operations was that you upgraded to 3.0.4 after the April content release -- total shot in the dark. The only other idea is that the cached manifest wasn't updated properly by whoever hit the instance of the viewer web part after the update was dropped and the cache expired. When learning pathways installs it sets the access to the custom config list for everyone to have edit/contribute permissions so maybe that's the problem.

Also, is it possible that in this step:

> After the April 20 content update, custom created sub categories in their installation no longer show in the LearningViewer, despite having the eye icon enabled. They were visible prior.
Clicking the eye on or off changes the icon but CustomLearningViewer still refuse to show them.

You just had two tabs open and were doing things in the admin and not "reloading" the page with the viewer web part on it. Once the page loads just because you hit the admin web part the viewer web part doesn't pick up any changes until after you reload it so it can load the cached metadata again. We're not using WebSockets technology so you have to refresh the page to see any changes made in the admin web part.

**Comment by tomrune** [comment]
Unfortunately, I have no control over this customer's environment. I am admin in our tenant, but while they have provided me with a user in their tenant, it has limited access in their environment (Site member in the learning pathway site), so all is limited to what I can ask them to look up for me and what I can sleuth my way to myself. 

I asked them what version they have, so I wouldn't rule out that they went ahead and updated then? I have been careful based on reading other similar threads to avoid the two tabs problems. I lean towards them perhaps updating the solution post the april refresh.

**Comment by tomrune** [comment]
> You just had two tabs open and were doing things in the admin and not "reloading" the page with the viewer web part on it. Once the page loads just because you hit the admin web part the viewer web part doesn't pick up any changes until after you reload it so it can load the cached metadata again. We're not using WebSockets technology so you have to refresh the page to see any changes made in the admin web part.

I believe it was more related to the fact that a subcategory without playlists don't appear, so subcategories with playlists without a technology set would behave like a subcategory without any playlists at all.

**Comment by foxward** [comment]
@juliemturner @tomrune 
I'm having this same issue. Created a new subcategory, created new assets to make a playlist, the playlists are not visible with no eye icon. 

I've added a technology to both the playlist and the new assets, still not visible. I've removed the technology from the playlist and the assets, still not visible. 

Yesterday they weren't visible. I closed all browser windows and opened, and voila! they were visible. But gone back in today and they are not visible again.

**Comment by juliemturner** [comment]
First let me please ask that no one continue to talk about their related issue on a closed issue. These things can easily fall through the cracks.  If you're experiencing a similar issue please open a new issue and feel free to reference by using the #{issue #} reference.  

Happy to help here @foxward, if you could start your own issue that would be useful, please make sure you're using the latest version.  Also, closing the browser windows is not required but refreshing the page is as the cache is in a list item and there is no "push" that the item has been updated, you must initiate a pull by refreshing the page... long story short if you change something int he admin web part you need to refresh the viewer web part to see it.  Also, you want to double-check that you've not hidden any technologies and are then applying those hidden technologies to your playlists or assets.
