### ISSUE TITLE
 URLs of support.microsoft.com Content Changed Without Warning.

### ISSUE THREAD

**Issue by AaronKGumbs** [pnp/custom-learning-office-365#699]
## Describe the bug

Seemingly overnight, some URLs within the support.microsoft.com domain have been changed, leading to content not being displayed and confusion about how to reconfigure the playlists. The original working assets, as well as the old working URL, now point to a page that says:

"Need assistance? Use the search box to tell us what you're looking for or browse for content on the Office help and training site."

When you try to re-configure the playlist with the new asset, duplicates appear and it's guesswork on which one should be selected.

### To Reproduce

Create a custom playlist with the OneNote 'Take Notes' asset.

### Expected behavior

The URLs should re-direct to the newly hosted pages or the content should've been published on the original URL.

### Learning Pathways version number

To be confirmed once sys admin is available.

**Comment by AaronKGumbs** [comment]
Hey @dcashpeterson, we are working with our community managers to understand the scale and scope of the issue as we speak. Comms were sent out to our clients yesterday so I'll let you know of any replies as soon as I hear. The challenge we have is that all clients have a different mix of assets so it's not as quick to identify as I'd like!

**Comment by AaronKGumbs** [comment]
Hey @dcashpeterson, we're seeing issues with all of the assets shown in this screenshot. Only Take Notes shows an alternative, and the rest didn't when we last checked.

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/26457537/194593766-94604cd3-45b0-4eeb-9bb1-e3a21129b495.png)

**Comment by dcashpeterson** [comment]
@AaronKGumbs I was able to get a hold of this one and it looks like there are two issues. 
1. There are two Take Notes, one that works and one that doesn't. 
2. The other links in the manifest file are broken. 

I will work with the content team to get this resolved and update you when we have deployed the update.

**Comment by dcashpeterson** [comment]
Update on this. We are still waiting on a content update. @peterjkrebs do you have an update on when this can be fixed?

**Comment by frkl1103** [comment]
@dcashpeterson Any news yet on when the issue will be resolved? 
We are currently in a Microsoft 365 implementation and are using the Learning Pathway. In this process, we also noticed the error with the OneNote Quick Start pages (take notes, share and stay organized, set up your mobile apps).

**Comment by dcashpeterson** [comment]
@frkl1103 I am working on getting an update from the content team.

**Comment by frkl1103** [comment]
@dcashpeterson  Any news on that?

**Comment by dcashpeterson** [comment]
@frkl1103 The issue with the broken OneNote items has been resolved and is live. There are still two Take Notes assets but we will fix that in the next content release.

**Comment by dcashpeterson** [comment]
@jhwang-ms one more thing to add to the next content update. Remove the duplicate Take Notes entry.

**Comment by frkl1103** [comment]
> @frkl1103 The issue with the broken OneNote items has been resolved and is live. There are still two Take Notes assets but we will fix that in the next content release.

@dcashpeterson It seems that the issue with the broken OneNote items has been resolved **only in the Englisch version**. We are using the German version and the OneNote Quick Start pages (take notes, share and stay organized, set up your mobile apps) are still broken.

**Comment by CSViviandee** [comment]
Just wanted to check if this issue has been resolved, we are also experiencing this issue where only the OneNote Quick start is working and the other ones are all broken.

**Comment by dcashpeterson** [comment]
@CSViviandee no this issue has not been resolved with the other Learning Pathways languages. It is on our radar to resolve. @jhwang-ms

**Comment by dcashpeterson** [comment]
@AaronKGumbs and @CSViviandee  This has been a long time coming but I have rolled out a fix for the OneNote content issues. You will need to clear the cache in Learning Pathways to see the changes. This should be rolled out to all languages.

Please let me know if there are any issues and reference this issue.
